spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: file://${user.dir}/../config-repo
server:
  port: 8070
eureka :
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true                       # 设置微服务调用地址为IP优先（缺省为false）
    lease-renewal-interval-in-seconds: 5          # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15      # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    healthcheck:
      enabled: true
    serviceUrl :
      defaultZone : http://localhost:8090/eureka/
